# CMake generated Testfile for 
# Source directory: /root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/preflowpush
# Build directory: /root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/analytics/cpu/preflowpush
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(run-small1-preflowpush-cpu-32 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/analytics/cpu/preflowpush/preflowpush-cpu" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/reference/structured/torus5.gr" "-sourceNode=0" "-sinkNode=10" "-t" "32")
set_tests_properties(run-small1-preflowpush-cpu-32 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/preflowpush/CMakeLists.txt;5;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/preflowpush/CMakeLists.txt;0;")
add_test(run-small1-preflowpush-cpu-16 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/analytics/cpu/preflowpush/preflowpush-cpu" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/reference/structured/torus5.gr" "-sourceNode=0" "-sinkNode=10" "-t" "16")
set_tests_properties(run-small1-preflowpush-cpu-16 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/preflowpush/CMakeLists.txt;5;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/preflowpush/CMakeLists.txt;0;")
add_test(run-small1-preflowpush-cpu-8 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/analytics/cpu/preflowpush/preflowpush-cpu" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/reference/structured/torus5.gr" "-sourceNode=0" "-sinkNode=10" "-t" "8")
set_tests_properties(run-small1-preflowpush-cpu-8 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/preflowpush/CMakeLists.txt;5;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/preflowpush/CMakeLists.txt;0;")
add_test(run-small1-preflowpush-cpu-4 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/analytics/cpu/preflowpush/preflowpush-cpu" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/reference/structured/torus5.gr" "-sourceNode=0" "-sinkNode=10" "-t" "4")
set_tests_properties(run-small1-preflowpush-cpu-4 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/preflowpush/CMakeLists.txt;5;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/preflowpush/CMakeLists.txt;0;")
add_test(run-small1-preflowpush-cpu-2 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/analytics/cpu/preflowpush/preflowpush-cpu" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/reference/structured/torus5.gr" "-sourceNode=0" "-sinkNode=10" "-t" "2")
set_tests_properties(run-small1-preflowpush-cpu-2 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/preflowpush/CMakeLists.txt;5;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/preflowpush/CMakeLists.txt;0;")
add_test(run-small1-preflowpush-cpu-1 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/analytics/cpu/preflowpush/preflowpush-cpu" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/reference/structured/torus5.gr" "-sourceNode=0" "-sinkNode=10" "-t" "1")
set_tests_properties(run-small1-preflowpush-cpu-1 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/preflowpush/CMakeLists.txt;5;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/preflowpush/CMakeLists.txt;0;")
