# CMake generated Testfile for 
# Source directory: /root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/delaunayrefinement
# Build directory: /root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/scientific/cpu/delaunayrefinement
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(run-small1-delaunayrefinement-cpu-32 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/scientific/cpu/delaunayrefinement/delaunayrefinement-cpu" "-meshGraph" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/reference/meshes/r10k.1" "-t" "32")
set_tests_properties(run-small1-delaunayrefinement-cpu-32 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/delaunayrefinement/CMakeLists.txt;10;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/delaunayrefinement/CMakeLists.txt;0;")
add_test(run-small1-delaunayrefinement-cpu-16 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/scientific/cpu/delaunayrefinement/delaunayrefinement-cpu" "-meshGraph" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/reference/meshes/r10k.1" "-t" "16")
set_tests_properties(run-small1-delaunayrefinement-cpu-16 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/delaunayrefinement/CMakeLists.txt;10;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/delaunayrefinement/CMakeLists.txt;0;")
add_test(run-small1-delaunayrefinement-cpu-8 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/scientific/cpu/delaunayrefinement/delaunayrefinement-cpu" "-meshGraph" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/reference/meshes/r10k.1" "-t" "8")
set_tests_properties(run-small1-delaunayrefinement-cpu-8 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/delaunayrefinement/CMakeLists.txt;10;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/delaunayrefinement/CMakeLists.txt;0;")
add_test(run-small1-delaunayrefinement-cpu-4 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/scientific/cpu/delaunayrefinement/delaunayrefinement-cpu" "-meshGraph" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/reference/meshes/r10k.1" "-t" "4")
set_tests_properties(run-small1-delaunayrefinement-cpu-4 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/delaunayrefinement/CMakeLists.txt;10;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/delaunayrefinement/CMakeLists.txt;0;")
add_test(run-small1-delaunayrefinement-cpu-2 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/scientific/cpu/delaunayrefinement/delaunayrefinement-cpu" "-meshGraph" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/reference/meshes/r10k.1" "-t" "2")
set_tests_properties(run-small1-delaunayrefinement-cpu-2 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/delaunayrefinement/CMakeLists.txt;10;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/delaunayrefinement/CMakeLists.txt;0;")
add_test(run-small1-delaunayrefinement-cpu-1 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/scientific/cpu/delaunayrefinement/delaunayrefinement-cpu" "-meshGraph" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/reference/meshes/r10k.1" "-t" "1")
set_tests_properties(run-small1-delaunayrefinement-cpu-1 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/delaunayrefinement/CMakeLists.txt;10;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/delaunayrefinement/CMakeLists.txt;0;")
add_test(run-small2-delaunayrefinement-cpu-32 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/scientific/cpu/delaunayrefinement/delaunayrefinement-cpu" "-meshGraph" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/meshes/250k.2" "-t" "32")
set_tests_properties(run-small2-delaunayrefinement-cpu-32 PROPERTIES  _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/delaunayrefinement/CMakeLists.txt;11;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/delaunayrefinement/CMakeLists.txt;0;")
add_test(run-small2-delaunayrefinement-cpu-16 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/scientific/cpu/delaunayrefinement/delaunayrefinement-cpu" "-meshGraph" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/meshes/250k.2" "-t" "16")
set_tests_properties(run-small2-delaunayrefinement-cpu-16 PROPERTIES  _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/delaunayrefinement/CMakeLists.txt;11;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/delaunayrefinement/CMakeLists.txt;0;")
add_test(run-small2-delaunayrefinement-cpu-8 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/scientific/cpu/delaunayrefinement/delaunayrefinement-cpu" "-meshGraph" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/meshes/250k.2" "-t" "8")
set_tests_properties(run-small2-delaunayrefinement-cpu-8 PROPERTIES  _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/delaunayrefinement/CMakeLists.txt;11;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/delaunayrefinement/CMakeLists.txt;0;")
add_test(run-small2-delaunayrefinement-cpu-4 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/scientific/cpu/delaunayrefinement/delaunayrefinement-cpu" "-meshGraph" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/meshes/250k.2" "-t" "4")
set_tests_properties(run-small2-delaunayrefinement-cpu-4 PROPERTIES  _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/delaunayrefinement/CMakeLists.txt;11;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/delaunayrefinement/CMakeLists.txt;0;")
add_test(run-small2-delaunayrefinement-cpu-2 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/scientific/cpu/delaunayrefinement/delaunayrefinement-cpu" "-meshGraph" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/meshes/250k.2" "-t" "2")
set_tests_properties(run-small2-delaunayrefinement-cpu-2 PROPERTIES  _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/delaunayrefinement/CMakeLists.txt;11;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/delaunayrefinement/CMakeLists.txt;0;")
add_test(run-small2-delaunayrefinement-cpu-1 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/scientific/cpu/delaunayrefinement/delaunayrefinement-cpu" "-meshGraph" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/meshes/250k.2" "-t" "1")
set_tests_properties(run-small2-delaunayrefinement-cpu-1 PROPERTIES  _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/delaunayrefinement/CMakeLists.txt;11;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/delaunayrefinement/CMakeLists.txt;0;")
