# CMake generated Testfile for 
# Source directory: /root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/tools/graph-convert
# Build directory: /root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/tools/graph-convert
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(create-edgelist2gr-gr2edgelist-test-inputs/with-blank-lines.edgelist "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/tools/graph-convert/graph-convert" "-edgelist2gr" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/tools/graph-convert/test-inputs/with-blank-lines.edgelist" "with-blank-lines.edgelist.test")
set_tests_properties(create-edgelist2gr-gr2edgelist-test-inputs/with-blank-lines.edgelist PROPERTIES  LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/tools/graph-convert/CMakeLists.txt;14;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/tools/graph-convert/CMakeLists.txt;32;compare_with_sample;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/tools/graph-convert/CMakeLists.txt;0;")
add_test(convert-edgelist2gr-gr2edgelist-test-inputs/with-blank-lines.edgelist "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/tools/graph-convert/graph-convert" "-gr2edgelist" "with-blank-lines.edgelist.test" "with-blank-lines.edgelist.compare")
set_tests_properties(convert-edgelist2gr-gr2edgelist-test-inputs/with-blank-lines.edgelist PROPERTIES  DEPENDS "create-edgelist2gr-gr2edgelist-test-inputs/with-blank-lines.edgelist" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/tools/graph-convert/CMakeLists.txt;19;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/tools/graph-convert/CMakeLists.txt;32;compare_with_sample;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/tools/graph-convert/CMakeLists.txt;0;")
add_test(compare-edgelist2gr-gr2edgelist-test-inputs/with-blank-lines.edgelist "/usr/local/bin/cmake" "-E" "compare_files" "with-blank-lines.edgelist.compare" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/tools/graph-convert/test-inputs/with-blank-lines.edgelist.expected")
set_tests_properties(compare-edgelist2gr-gr2edgelist-test-inputs/with-blank-lines.edgelist PROPERTIES  DEPENDS "convert-edgelist2gr-gr2edgelist-test-inputs/with-blank-lines.edgelist" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/tools/graph-convert/CMakeLists.txt;25;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/tools/graph-convert/CMakeLists.txt;32;compare_with_sample;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/tools/graph-convert/CMakeLists.txt;0;")
add_test(create-csv2gr-gr2edgelist-test-inputs/sample.csv "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/tools/graph-convert/graph-convert" "-csv2gr" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/tools/graph-convert/test-inputs/sample.csv" "sample.csv.test")
set_tests_properties(create-csv2gr-gr2edgelist-test-inputs/sample.csv PROPERTIES  LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/tools/graph-convert/CMakeLists.txt;14;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/tools/graph-convert/CMakeLists.txt;33;compare_with_sample;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/tools/graph-convert/CMakeLists.txt;0;")
add_test(convert-csv2gr-gr2edgelist-test-inputs/sample.csv "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/tools/graph-convert/graph-convert" "-gr2edgelist" "sample.csv.test" "sample.csv.compare")
set_tests_properties(convert-csv2gr-gr2edgelist-test-inputs/sample.csv PROPERTIES  DEPENDS "create-csv2gr-gr2edgelist-test-inputs/sample.csv" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/tools/graph-convert/CMakeLists.txt;19;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/tools/graph-convert/CMakeLists.txt;33;compare_with_sample;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/tools/graph-convert/CMakeLists.txt;0;")
add_test(compare-csv2gr-gr2edgelist-test-inputs/sample.csv "/usr/local/bin/cmake" "-E" "compare_files" "sample.csv.compare" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/tools/graph-convert/test-inputs/with-blank-lines.edgelist.expected")
set_tests_properties(compare-csv2gr-gr2edgelist-test-inputs/sample.csv PROPERTIES  DEPENDS "convert-csv2gr-gr2edgelist-test-inputs/sample.csv" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/tools/graph-convert/CMakeLists.txt;25;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/tools/graph-convert/CMakeLists.txt;33;compare_with_sample;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/tools/graph-convert/CMakeLists.txt;0;")
add_test(create-edgelist2gr-gr2edgelist-test-inputs/with-comments.edgelist "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/tools/graph-convert/graph-convert" "-edgelist2gr" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/tools/graph-convert/test-inputs/with-comments.edgelist" "with-comments.edgelist.test")
set_tests_properties(create-edgelist2gr-gr2edgelist-test-inputs/with-comments.edgelist PROPERTIES  LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/tools/graph-convert/CMakeLists.txt;14;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/tools/graph-convert/CMakeLists.txt;34;compare_with_sample;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/tools/graph-convert/CMakeLists.txt;0;")
add_test(convert-edgelist2gr-gr2edgelist-test-inputs/with-comments.edgelist "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/tools/graph-convert/graph-convert" "-gr2edgelist" "with-comments.edgelist.test" "with-comments.edgelist.compare")
set_tests_properties(convert-edgelist2gr-gr2edgelist-test-inputs/with-comments.edgelist PROPERTIES  DEPENDS "create-edgelist2gr-gr2edgelist-test-inputs/with-comments.edgelist" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/tools/graph-convert/CMakeLists.txt;19;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/tools/graph-convert/CMakeLists.txt;34;compare_with_sample;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/tools/graph-convert/CMakeLists.txt;0;")
add_test(compare-edgelist2gr-gr2edgelist-test-inputs/with-comments.edgelist "/usr/local/bin/cmake" "-E" "compare_files" "with-comments.edgelist.compare" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/tools/graph-convert/test-inputs/with-comments.edgelist.expected")
set_tests_properties(compare-edgelist2gr-gr2edgelist-test-inputs/with-comments.edgelist PROPERTIES  DEPENDS "convert-edgelist2gr-gr2edgelist-test-inputs/with-comments.edgelist" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/tools/graph-convert/CMakeLists.txt;25;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/tools/graph-convert/CMakeLists.txt;34;compare_with_sample;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/tools/graph-convert/CMakeLists.txt;0;")
