# CMake generated Testfile for 
# Source directory: /root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/barneshut
# Build directory: /root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/scientific/cpu/barneshut
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(run-small-barneshut-cpu-32 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/scientific/cpu/barneshut/barneshut-cpu" "-n" "10000" "-steps" "1" "-seed" "0" "-t" "32")
set_tests_properties(run-small-barneshut-cpu-32 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/barneshut/CMakeLists.txt;10;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/barneshut/CMakeLists.txt;0;")
add_test(run-small-barneshut-cpu-16 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/scientific/cpu/barneshut/barneshut-cpu" "-n" "10000" "-steps" "1" "-seed" "0" "-t" "16")
set_tests_properties(run-small-barneshut-cpu-16 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/barneshut/CMakeLists.txt;10;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/barneshut/CMakeLists.txt;0;")
add_test(run-small-barneshut-cpu-8 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/scientific/cpu/barneshut/barneshut-cpu" "-n" "10000" "-steps" "1" "-seed" "0" "-t" "8")
set_tests_properties(run-small-barneshut-cpu-8 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/barneshut/CMakeLists.txt;10;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/barneshut/CMakeLists.txt;0;")
add_test(run-small-barneshut-cpu-4 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/scientific/cpu/barneshut/barneshut-cpu" "-n" "10000" "-steps" "1" "-seed" "0" "-t" "4")
set_tests_properties(run-small-barneshut-cpu-4 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/barneshut/CMakeLists.txt;10;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/barneshut/CMakeLists.txt;0;")
add_test(run-small-barneshut-cpu-2 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/scientific/cpu/barneshut/barneshut-cpu" "-n" "10000" "-steps" "1" "-seed" "0" "-t" "2")
set_tests_properties(run-small-barneshut-cpu-2 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/barneshut/CMakeLists.txt;10;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/barneshut/CMakeLists.txt;0;")
add_test(run-small-barneshut-cpu-1 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/scientific/cpu/barneshut/barneshut-cpu" "-n" "10000" "-steps" "1" "-seed" "0" "-t" "1")
set_tests_properties(run-small-barneshut-cpu-1 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/barneshut/CMakeLists.txt;10;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/scientific/cpu/barneshut/CMakeLists.txt;0;")
