# CMake generated Testfile for 
# Source directory: /root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/matching
# Build directory: /root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/analytics/cpu/matching
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(run-small1-maximum-cardinality-matching-cpu-32 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/analytics/cpu/matching/maximum-cardinality-matching-cpu" "-symmetricGraph" "-inputType" "generated" "-n" "100" "-numEdges" "1000" "-numGroups" "10" "-seed" "0" "-t" "32")
set_tests_properties(run-small1-maximum-cardinality-matching-cpu-32 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/matching/CMakeLists.txt;6;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/matching/CMakeLists.txt;0;")
add_test(run-small1-maximum-cardinality-matching-cpu-16 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/analytics/cpu/matching/maximum-cardinality-matching-cpu" "-symmetricGraph" "-inputType" "generated" "-n" "100" "-numEdges" "1000" "-numGroups" "10" "-seed" "0" "-t" "16")
set_tests_properties(run-small1-maximum-cardinality-matching-cpu-16 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/matching/CMakeLists.txt;6;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/matching/CMakeLists.txt;0;")
add_test(run-small1-maximum-cardinality-matching-cpu-8 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/analytics/cpu/matching/maximum-cardinality-matching-cpu" "-symmetricGraph" "-inputType" "generated" "-n" "100" "-numEdges" "1000" "-numGroups" "10" "-seed" "0" "-t" "8")
set_tests_properties(run-small1-maximum-cardinality-matching-cpu-8 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/matching/CMakeLists.txt;6;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/matching/CMakeLists.txt;0;")
add_test(run-small1-maximum-cardinality-matching-cpu-4 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/analytics/cpu/matching/maximum-cardinality-matching-cpu" "-symmetricGraph" "-inputType" "generated" "-n" "100" "-numEdges" "1000" "-numGroups" "10" "-seed" "0" "-t" "4")
set_tests_properties(run-small1-maximum-cardinality-matching-cpu-4 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/matching/CMakeLists.txt;6;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/matching/CMakeLists.txt;0;")
add_test(run-small1-maximum-cardinality-matching-cpu-2 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/analytics/cpu/matching/maximum-cardinality-matching-cpu" "-symmetricGraph" "-inputType" "generated" "-n" "100" "-numEdges" "1000" "-numGroups" "10" "-seed" "0" "-t" "2")
set_tests_properties(run-small1-maximum-cardinality-matching-cpu-2 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/matching/CMakeLists.txt;6;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/matching/CMakeLists.txt;0;")
add_test(run-small1-maximum-cardinality-matching-cpu-1 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/analytics/cpu/matching/maximum-cardinality-matching-cpu" "-symmetricGraph" "-inputType" "generated" "-n" "100" "-numEdges" "1000" "-numGroups" "10" "-seed" "0" "-t" "1")
set_tests_properties(run-small1-maximum-cardinality-matching-cpu-1 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/matching/CMakeLists.txt;6;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/matching/CMakeLists.txt;0;")
add_test(run-small2-maximum-cardinality-matching-cpu-32 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/analytics/cpu/matching/maximum-cardinality-matching-cpu" "-symmetricGraph" "-inputType" "generated" "-n" "100" "-numEdges" "10000" "-numGroups" "100" "-seed" "0" "-t" "32")
set_tests_properties(run-small2-maximum-cardinality-matching-cpu-32 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/matching/CMakeLists.txt;7;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/matching/CMakeLists.txt;0;")
add_test(run-small2-maximum-cardinality-matching-cpu-16 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/analytics/cpu/matching/maximum-cardinality-matching-cpu" "-symmetricGraph" "-inputType" "generated" "-n" "100" "-numEdges" "10000" "-numGroups" "100" "-seed" "0" "-t" "16")
set_tests_properties(run-small2-maximum-cardinality-matching-cpu-16 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/matching/CMakeLists.txt;7;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/matching/CMakeLists.txt;0;")
add_test(run-small2-maximum-cardinality-matching-cpu-8 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/analytics/cpu/matching/maximum-cardinality-matching-cpu" "-symmetricGraph" "-inputType" "generated" "-n" "100" "-numEdges" "10000" "-numGroups" "100" "-seed" "0" "-t" "8")
set_tests_properties(run-small2-maximum-cardinality-matching-cpu-8 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/matching/CMakeLists.txt;7;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/matching/CMakeLists.txt;0;")
add_test(run-small2-maximum-cardinality-matching-cpu-4 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/analytics/cpu/matching/maximum-cardinality-matching-cpu" "-symmetricGraph" "-inputType" "generated" "-n" "100" "-numEdges" "10000" "-numGroups" "100" "-seed" "0" "-t" "4")
set_tests_properties(run-small2-maximum-cardinality-matching-cpu-4 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/matching/CMakeLists.txt;7;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/matching/CMakeLists.txt;0;")
add_test(run-small2-maximum-cardinality-matching-cpu-2 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/analytics/cpu/matching/maximum-cardinality-matching-cpu" "-symmetricGraph" "-inputType" "generated" "-n" "100" "-numEdges" "10000" "-numGroups" "100" "-seed" "0" "-t" "2")
set_tests_properties(run-small2-maximum-cardinality-matching-cpu-2 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/matching/CMakeLists.txt;7;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/matching/CMakeLists.txt;0;")
add_test(run-small2-maximum-cardinality-matching-cpu-1 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/analytics/cpu/matching/maximum-cardinality-matching-cpu" "-symmetricGraph" "-inputType" "generated" "-n" "100" "-numEdges" "10000" "-numGroups" "100" "-seed" "0" "-t" "1")
set_tests_properties(run-small2-maximum-cardinality-matching-cpu-1 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/matching/CMakeLists.txt;7;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/analytics/cpu/matching/CMakeLists.txt;0;")
