# CMake generated Testfile for 
# Source directory: /root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/mining/cpu/triangle-counting
# Build directory: /root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/mining/cpu/triangle-counting
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(run-small1-triangle-counting-mining-cpu-32 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/mining/cpu/triangle-counting/triangle-counting-mining-cpu" "-symmetricGraph" "-simpleGraph" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/Mining/citeseer.csgr" "-t" "32")
set_tests_properties(run-small1-triangle-counting-mining-cpu-32 PROPERTIES  _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/mining/cpu/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/mining/cpu/triangle-counting/CMakeLists.txt;6;add_test_mine;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/mining/cpu/triangle-counting/CMakeLists.txt;0;")
add_test(run-small1-triangle-counting-mining-cpu-16 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/mining/cpu/triangle-counting/triangle-counting-mining-cpu" "-symmetricGraph" "-simpleGraph" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/Mining/citeseer.csgr" "-t" "16")
set_tests_properties(run-small1-triangle-counting-mining-cpu-16 PROPERTIES  _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/mining/cpu/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/mining/cpu/triangle-counting/CMakeLists.txt;6;add_test_mine;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/mining/cpu/triangle-counting/CMakeLists.txt;0;")
add_test(run-small1-triangle-counting-mining-cpu-8 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/mining/cpu/triangle-counting/triangle-counting-mining-cpu" "-symmetricGraph" "-simpleGraph" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/Mining/citeseer.csgr" "-t" "8")
set_tests_properties(run-small1-triangle-counting-mining-cpu-8 PROPERTIES  _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/mining/cpu/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/mining/cpu/triangle-counting/CMakeLists.txt;6;add_test_mine;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/mining/cpu/triangle-counting/CMakeLists.txt;0;")
add_test(run-small1-triangle-counting-mining-cpu-4 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/mining/cpu/triangle-counting/triangle-counting-mining-cpu" "-symmetricGraph" "-simpleGraph" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/Mining/citeseer.csgr" "-t" "4")
set_tests_properties(run-small1-triangle-counting-mining-cpu-4 PROPERTIES  _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/mining/cpu/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/mining/cpu/triangle-counting/CMakeLists.txt;6;add_test_mine;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/mining/cpu/triangle-counting/CMakeLists.txt;0;")
add_test(run-small1-triangle-counting-mining-cpu-2 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/mining/cpu/triangle-counting/triangle-counting-mining-cpu" "-symmetricGraph" "-simpleGraph" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/Mining/citeseer.csgr" "-t" "2")
set_tests_properties(run-small1-triangle-counting-mining-cpu-2 PROPERTIES  _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/mining/cpu/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/mining/cpu/triangle-counting/CMakeLists.txt;6;add_test_mine;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/mining/cpu/triangle-counting/CMakeLists.txt;0;")
add_test(run-small1-triangle-counting-mining-cpu-1 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/mining/cpu/triangle-counting/triangle-counting-mining-cpu" "-symmetricGraph" "-simpleGraph" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/Mining/citeseer.csgr" "-t" "1")
set_tests_properties(run-small1-triangle-counting-mining-cpu-1 PROPERTIES  _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/mining/cpu/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/mining/cpu/triangle-counting/CMakeLists.txt;6;add_test_mine;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/mining/cpu/triangle-counting/CMakeLists.txt;0;")
