# CMake generated Testfile for 
# Source directory: /root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/eda/cpu/aig-rewriting
# Build directory: /root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/eda/cpu/aig-rewriting
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(run-small1-aig-rewriting-cpu-32 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/eda/cpu/aig-rewriting/aig-rewriting-cpu" "-AIG" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/eda/logic-synthesis/EPFL/arithmetic/adder/aiger/adder.aig" "-v" "-t" "32")
set_tests_properties(run-small1-aig-rewriting-cpu-32 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/eda/cpu/aig-rewriting/CMakeLists.txt;27;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/eda/cpu/aig-rewriting/CMakeLists.txt;0;")
add_test(run-small1-aig-rewriting-cpu-16 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/eda/cpu/aig-rewriting/aig-rewriting-cpu" "-AIG" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/eda/logic-synthesis/EPFL/arithmetic/adder/aiger/adder.aig" "-v" "-t" "16")
set_tests_properties(run-small1-aig-rewriting-cpu-16 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/eda/cpu/aig-rewriting/CMakeLists.txt;27;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/eda/cpu/aig-rewriting/CMakeLists.txt;0;")
add_test(run-small1-aig-rewriting-cpu-8 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/eda/cpu/aig-rewriting/aig-rewriting-cpu" "-AIG" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/eda/logic-synthesis/EPFL/arithmetic/adder/aiger/adder.aig" "-v" "-t" "8")
set_tests_properties(run-small1-aig-rewriting-cpu-8 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/eda/cpu/aig-rewriting/CMakeLists.txt;27;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/eda/cpu/aig-rewriting/CMakeLists.txt;0;")
add_test(run-small1-aig-rewriting-cpu-4 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/eda/cpu/aig-rewriting/aig-rewriting-cpu" "-AIG" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/eda/logic-synthesis/EPFL/arithmetic/adder/aiger/adder.aig" "-v" "-t" "4")
set_tests_properties(run-small1-aig-rewriting-cpu-4 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/eda/cpu/aig-rewriting/CMakeLists.txt;27;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/eda/cpu/aig-rewriting/CMakeLists.txt;0;")
add_test(run-small1-aig-rewriting-cpu-2 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/eda/cpu/aig-rewriting/aig-rewriting-cpu" "-AIG" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/eda/logic-synthesis/EPFL/arithmetic/adder/aiger/adder.aig" "-v" "-t" "2")
set_tests_properties(run-small1-aig-rewriting-cpu-2 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/eda/cpu/aig-rewriting/CMakeLists.txt;27;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/eda/cpu/aig-rewriting/CMakeLists.txt;0;")
add_test(run-small1-aig-rewriting-cpu-1 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/eda/cpu/aig-rewriting/aig-rewriting-cpu" "-AIG" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/eda/logic-synthesis/EPFL/arithmetic/adder/aiger/adder.aig" "-v" "-t" "1")
set_tests_properties(run-small1-aig-rewriting-cpu-1 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/eda/cpu/aig-rewriting/CMakeLists.txt;27;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/eda/cpu/aig-rewriting/CMakeLists.txt;0;")
add_test(run-small2-aig-rewriting-cpu-32 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/eda/cpu/aig-rewriting/aig-rewriting-cpu" "-AIG" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/eda/logic-synthesis/EPFL/random_control/voter/aiger/voter.aig" "-v" "-t" "32")
set_tests_properties(run-small2-aig-rewriting-cpu-32 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/eda/cpu/aig-rewriting/CMakeLists.txt;28;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/eda/cpu/aig-rewriting/CMakeLists.txt;0;")
add_test(run-small2-aig-rewriting-cpu-16 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/eda/cpu/aig-rewriting/aig-rewriting-cpu" "-AIG" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/eda/logic-synthesis/EPFL/random_control/voter/aiger/voter.aig" "-v" "-t" "16")
set_tests_properties(run-small2-aig-rewriting-cpu-16 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/eda/cpu/aig-rewriting/CMakeLists.txt;28;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/eda/cpu/aig-rewriting/CMakeLists.txt;0;")
add_test(run-small2-aig-rewriting-cpu-8 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/eda/cpu/aig-rewriting/aig-rewriting-cpu" "-AIG" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/eda/logic-synthesis/EPFL/random_control/voter/aiger/voter.aig" "-v" "-t" "8")
set_tests_properties(run-small2-aig-rewriting-cpu-8 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/eda/cpu/aig-rewriting/CMakeLists.txt;28;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/eda/cpu/aig-rewriting/CMakeLists.txt;0;")
add_test(run-small2-aig-rewriting-cpu-4 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/eda/cpu/aig-rewriting/aig-rewriting-cpu" "-AIG" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/eda/logic-synthesis/EPFL/random_control/voter/aiger/voter.aig" "-v" "-t" "4")
set_tests_properties(run-small2-aig-rewriting-cpu-4 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/eda/cpu/aig-rewriting/CMakeLists.txt;28;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/eda/cpu/aig-rewriting/CMakeLists.txt;0;")
add_test(run-small2-aig-rewriting-cpu-2 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/eda/cpu/aig-rewriting/aig-rewriting-cpu" "-AIG" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/eda/logic-synthesis/EPFL/random_control/voter/aiger/voter.aig" "-v" "-t" "2")
set_tests_properties(run-small2-aig-rewriting-cpu-2 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/eda/cpu/aig-rewriting/CMakeLists.txt;28;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/eda/cpu/aig-rewriting/CMakeLists.txt;0;")
add_test(run-small2-aig-rewriting-cpu-1 "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/lonestar/eda/cpu/aig-rewriting/aig-rewriting-cpu" "-AIG" "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/build_newgr/inputs/eda/logic-synthesis/EPFL/random_control/voter/aiger/voter.aig" "-v" "-t" "1")
set_tests_properties(run-small2-aig-rewriting-cpu-1 PROPERTIES  ENVIRONMENT "GALOIS_DO_NOT_BIND_THREADS=1" LABELS "quick" _BACKTRACE_TRIPLES "/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/CMakeLists.txt;17;add_test;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/eda/cpu/aig-rewriting/CMakeLists.txt;28;add_test_scale;/root/OpenROAD_New_GRT/src/grt/src/NEWGR/Galois/lonestar/eda/cpu/aig-rewriting/CMakeLists.txt;0;")
